import '../styles/styles.css'
import '../styles/main.css'
import '../styles/product.css'
import '../styles/payment.css'
import Nav from '../components/nav';
import Footer from '../components/footer';
import { Open_Sans } from 'next/font/google';
import { CookiesProvider } from 'next-client-cookies/server';
import { LoadingProvider } from '../contexts/loading';
import { SessionProvider } from '../contexts/session';
export const metadata = {
  title: 'Welcome to storefront',
  description: 'Generated by create-nx-workspace',
};

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '700'], // Specify the weights you need
  style: ['normal', 'italic'], // Specify styles if needed
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body className={openSans.className}>
        <CookiesProvider>
          <SessionProvider>
          <LoadingProvider>
            <Nav />
            {children}
            <Footer />
          </LoadingProvider>
          </SessionProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
