import '../lib/styles/styles.css'
import '../lib/styles/main.css'
import Header from './components/header';
import Nav from './components/nav';
import Footer from './components/footer';
export const metadata = {
  title: 'Welcome to storefront',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body>
      <Header/>
      <Nav/>
        {children}
      <Footer/>

        </body>
    </html>
  );
}
