import { Fragment } from "react";
import SideBarProfile from "./sidebar";


export const metadata = {
    title: 'Welcome to storefront',
    description: 'Generated by create-nx-workspace',
};
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <Fragment>
             <div className="mt-5 container grid grid-cols-12 items-start gap-6 pt-4 pb-16">
            <SideBarProfile/>
            {children}
            </div>
        </Fragment>

    );
}
